### PR TITLE
fix(deps): mark `signal-polyfill` as a peer dependency

### PR DESCRIPTION
**Pull request by nicojs**
The `signal-utils` package provides a set of utilities for working with signals. It should not depend on the `signal-polyfill` directly, as it should allow users to choose their version of the polyfill.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
makes sense to me -- can you also update the README in the installation instructions to mention installing the polyfill?

**Comment by nicojs** [comment]
I could, but peer dependencies should be installed automatically by the package manager.

**Comment by NullVoxPopuli** [comment]
> I could, but peer dependencies should be installed automatically by the package manager.

only if enabled and for certain package managers, afaik -- many folks aren't even aware of this behavior :sweat_smile:

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by NullVoxPopuli** [comment]
thank you!!

**Pull request merged**
